# Правило редиректа для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Отключение кэширования для JSON
[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    Pragma = "no-cache"

# НОВАЯ ЧАСТЬ: Исправление ошибки MIME type
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"
